---
- name: Download OpenBao binary
  ansible.builtin.get_url:
    url: "{{ openbao_zip_url }}"
    dest: "/tmp/{{ openbao_pkg }}"
    owner: "root"
    group: "root"
    mode: "0755"
    checksum: "sha256:{{ (lookup('url', openbao_checksum_file_url, wantlist=true) | select('match', '.*' + openbao_pkg + '$') | first).split()[0] }}"
    validate_certs: false
  register: _download_server
  until: _download_server is succeeded
  retries: 5
  delay: 2

- name: Unarchive OpenBao
  ansible.builtin.unarchive:
    src: "/tmp/{{ openbao_pkg }}"
    dest: "/tmp/"
    creates: "/tmp/openbao"
    remote_src: true
  become: true
  run_once: true

- name: Install OpenBao
  become: true
  ansible.builtin.copy:
    src: "/tmp/openbao"
    dest: "{{ openbao_bin_path }}"
    owner: "{{ openbao_user }}"
    group: "{{ openbao_group }}"
    mode: "0755"
    remote_src: true
  notify: Restart OpenBao

- name: Clean up temporary files
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: "absent"
  with_items:
    - "/tmp/openbao"
    - "/tmp/{{ openbao_pkg }}"
