---

- name: Install utility packages
  ansible.builtin.package:
    name: '{{ item }}'
    state: 'present'
    update_cache: true
  become: true
  with_items:
    - curl
    - jq

- name: Copy OpenBao unseal script
  ansible.builtin.template:
    dest: "{{ openbao_config_path }}/openbao-unseal.sh"
    src: "openbao-unseal.sh.j2"
    owner: "{{ openbao_user }}"
    group: "{{ openbao_group }}"
    mode: "0744"
  become: true

- name: Create the OpenBao-unseal service systemd config
  ansible.builtin.template:
    src: openbao-unseal.service.j2
    dest: "/etc/systemd/system/openbao-unseal.service"
    owner: "root"
    group: "root"
    mode: "0644"
  become: true
  notify:
    - Reload OpenBao-unseal systemd service

- name: Ensure OpenBao-unseal is started at boot
  ansible.builtin.service:
    name: openbao-unseal
    enabled: true
  become: true
