---
- name: Create OpenBao unix group
  ansible.builtin.group:
    name: "{{ openbao_group }}"
    state: present

- name: Create OpenBao unix user
  ansible.builtin.user:
    name: "{{ openbao_user }}"
    group: "{{ openbao_group }}"
    system: "yes"
    shell: "/usr/sbin/nologin"

- name: Check OpenBao installation
  ansible.builtin.command: command -v bao
  environment:
    PATH: "{{ openbao_bin_path }}:{{ ansible_facts['env']['PATH'] }}"
  register: openbao_installation
  changed_when: false
  failed_when: false
  check_mode: false

- name: Get installed OpenBao version
  ansible.builtin.shell: |
    set -o pipefail
    {{ openbao_bin_path }}/bao -version | cut -d' ' -f2 | tr -d 'v'
  args:
    executable: /bin/bash
  when: openbao_installation.rc == 0
  changed_when: false
  check_mode: false
  register: installed_openbao_version

- name: Check if installation is required
  ansible.builtin.set_fact:
    installation_required: "{{ openbao_installation.rc != 0 or installed_openbao_version.stdout != openbao_version }}"

- name: Install OpenBao binary
  ansible.builtin.include_tasks: install_openbao.yml
  when: installation_required

- name: Create directories
  become: true
  ansible.builtin.file:
    dest: "{{ item }}"
    state: directory
    owner: "{{ openbao_user }}"
    group: "{{ openbao_group }}"
    mode: "0750"
  with_items:
    - "{{ openbao_config_path }}"
    - "{{ openbao_tls_path }}"
    - "{{ openbao_plugin_path }}"
    - "{{ openbao_policy_path }}"
    - "{{ openbao_data_path }}"
    - "{{ openbao_log_path }}"

- name: OpenBao main configuration
  become: true
  ansible.builtin.template:
    src: "openbao_main_configuration.json.j2"
    dest: "{{ openbao_main_config }}"
    owner: "{{ openbao_user }}"
    group: "{{ openbao_group }}"
    mode: "0400"
    backup: "true"
  notify:
    - Restart OpenBao
    - Reload OpenBao systemd

- name: Copy TLS private key file
  ansible.builtin.copy:
    dest: "{{ openbao_tls_path }}/openbao.key"
    content: "{{ openbao_key }}"
    owner: "{{ openbao_user }}"
    group: "{{ openbao_group }}"
    mode: "0644"
  become: true
  when: openbao_enable_tls
  notify: Restart OpenBao

- name: Copy cert file
  ansible.builtin.copy:
    dest: "{{ openbao_tls_path }}/openbao.crt"
    content: "{{ openbao_cert }}"
    owner: "{{ openbao_user }}"
    group: "{{ openbao_group }}"
    mode: "0644"
  become: true
  when: openbao_enable_tls
  notify: Restart OpenBao

- name: Copy CA cert file
  ansible.builtin.copy:
    dest: "{{ openbao_tls_path }}/openbao-ca.crt"
    content: "{{ openbao_ca }}"
    owner: "{{ openbao_user }}"
    group: "{{ openbao_group }}"
    mode: "0644"
  become: true
  when: openbao_enable_tls and custom_ca
  notify: Restart OpenBao

- name: Setup the OpenBao server systemd service
  ansible.builtin.template:
    src: openbao.service.j2
    dest: "/etc/systemd/system/openbao.service"
    owner: "root"
    group: "root"
    mode: "0644"
  notify:
    - Reload OpenBao systemd
    - Restart OpenBao

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Ensure OpenBao is started at boot
  ansible.builtin.service:
    name: openbao
    enabled: true

- name: Initialize OpenBao
  ansible.builtin.include_tasks: initialise_openbao.yml
  when: openbao_init

- name: Unseal OpenBao
  ansible.builtin.include_tasks: unseal_openbao.yml
  when: openbao_unseal

- name: Install OpenBao-unseal service
  ansible.builtin.include_tasks: install_unseal_service.yml
  when: openbao_unseal_service

- name: Run configuration tasks
  ansible.builtin.include_tasks:
    file: configure_openbao.yml
  when:
    - openbao_kv_secrets is defined
