---

- name: Check if OpenBao is sealed
  ansible.builtin.uri:
    url: "{{ openbao_api_dns_url }}/v1/sys/health"
    validate_certs: "{{ openbao_tls_skip_verify | ternary('false', 'true') }}"
    status_code: 200,429,472,501,503
  register: openbao_health_response
  run_once: true

- name: Unseal OpenBao
  ansible.builtin.uri:
    url: "{{ openbao_api_dns_url }}/v1/sys/unseal"
    body:
      key: "{{ item }}"
    body_format: json
    method: PUT
    validate_certs: "{{ openbao_tls_skip_verify | ternary('false', 'true') }}"
  register: unseal_openbao_response
  no_log: true
  run_once: true
  with_items:
    - "{{ openbao_keys }}"
  when:
    - openbao_health_response.status == 503
    - openbao_health_response.status != 501
    - openbao_keys is defined
