---

- name: Reload OpenBao systemd service
  ansible.builtin.systemd:
    name: openbao
    daemon_reload: true

- name: Reload OpenBao-unseal systemd service
  ansible.builtin.systemd:
    name: openbao-unseal
    daemon_reload: true

- name: Restart OpenBao
  ansible.builtin.service:
    name: openbao
    state: restarted
