---
name: CI/CD
'on':
  workflow_dispatch:
  pull_request:
    paths:
      - 'defaults/**'
      - 'handlers/**'
      - 'meta/**'
      - 'tasks/**'
      - 'templates/**'
      - 'vars/**'
      - 'tests/**'
      - '*.yml'
      - '*.yaml'
  push:
    branches:
      - main
    paths:
      - 'defaults/**'
      - 'handlers/**'
      - 'meta/**'
      - 'tasks/**'
      - 'templates/**'
      - 'vars/**'
      - 'tests/**'
      - '*.yml'
      - '*.yaml'

  schedule:
    - cron: "30 7 * * 3"

defaults:
  run:
    working-directory: 'olipinski.openbao'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v6
        with:
          path: 'olipinski.openbao'

      - name: Set up Python 3.
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip3 install yamllint ansible ansible-lint

      - name: Lint code.
        run: |
          yamllint .
          ansible-lint .
